runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 2

skip_files:
  - .*pdf$
  - .*csv$
  - .*zip$
  - .*_minted.*

handlers:
- url: /static
  static_dir: static